const applicationSectors = [
  "Financial",
  "Health and Fitness",
  "Education",
  "Entertainment",
  "Travel and Tourism",
  "Social Networking",
  "E-commerce",
  "Food and Beverage",
  "Transportation",
  "Real Estate",
  "Automotive",
  "Sports",
  "News and Media",
  "Weather",
  "Productivity",
  "Messaging",
  "Utilities",
  "Photography",
  "Art and Design",
  "Dating",
  "Gaming",
  "Music",
  "Shopping",
  "Business",
  "Lifestyle",
  "Navigation",
  "Weather",
  "Events",
  "Parenting",
  "Medical",
  "Government",
  "Charity and Non-profit",
  "Utilities",
  "Travel",
  "Fashion",
  "Books and Literature",
  "Home Improvement",
  "Comics",
  "Finance",
  "Healthcare",
  "Fitness",
  "Education",
  "Food and Drink",
  "Social",
  "Travel",
  "Technology",
  "Science",
  "Retail",
  "Marketing",
  "Beauty",
  "Automotive",
];
